final Map<String, dynamic> emotionSynonymsMap = {
  'alertness': ['Awareness', 'Consciousness'],
  'amusement': ['Entertainment', 'Delight', 'Merriment'],
  'awe': ['Admiration', 'Wonder', 'Reverence'],
  'gratitude': ['Thankfulness', 'Appreciation', 'Acknowledgment'],
  'hope': ['Optimism', 'Expectation', 'Confidence'],
  'joy': ['Happiness', 'Elation', 'Ecstasy'],
  'love': ['Affection', 'Adoration', 'Devotion'],
  'pride': ['Self-esteem', 'Satisfaction', 'Dignity'],
  'satisfaction': ['Contentment', 'Fulfillment', 'Pleasure'],
  'anger': ['Rage', 'Fury', 'Irritation'],
  'anxiety': ['Worry', 'Stress', 'Apprehension'],
  'contempt': ['Disdain', 'Scorn', 'Disrespect'],
  'disgust': ['Repulsion', 'Revulsion', 'Aversion'],
  'embarrassment': ['Shame', 'Awkwardness', 'Self-consciousness'],
  'fear': ['Terror', 'Dread', 'Panic'],
  'guilt': ['Remorse', 'Regret', 'Shame'],
  'offense': ['Indignation', 'Resentment', 'Hurt'],
  'sadness': ['Sorrow', 'Grief', 'Melancholy']
};
